# Generated by Django 4.0.4 on 2022-05-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('cantidad_stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
    ]
